// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-b7MOD-pS7PkYGezKel-ySlyjeL606A',
    appId: '1:722218540390:web:653035f69b5ffe1b5ebca7',
    messagingSenderId: '722218540390',
    projectId: 'yapo-2e6d1',
    authDomain: 'yapo-2e6d1.firebaseapp.com',
    databaseURL: 'https://yapo-2e6d1-default-rtdb.firebaseio.com',
    storageBucket: 'yapo-2e6d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4SfFC-s8S95-5DYCcNgOWLQgBEbyIRM',
    appId: '1:722218540390:android:a31ea12000ca30885ebca7',
    messagingSenderId: '722218540390',
    projectId: 'yapo-2e6d1',
    databaseURL: 'https://yapo-2e6d1-default-rtdb.firebaseio.com',
    storageBucket: 'yapo-2e6d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMDuhmxzRNoLzCG5NlZFkZ82GnKoGS80',
    appId: '1:722218540390:ios:12e971c76d041cde5ebca7',
    messagingSenderId: '722218540390',
    projectId: 'yapo-2e6d1',
    databaseURL: 'https://yapo-2e6d1-default-rtdb.firebaseio.com',
    storageBucket: 'yapo-2e6d1.appspot.com',
    androidClientId: '722218540390-9nuam8t3gekb0un5noeppgorpiktio1h.apps.googleusercontent.com',
    iosClientId: '722218540390-l1pf6ilg4akmfi8fgljjahdilej6h13b.apps.googleusercontent.com',
    iosBundleId: 'com.example.yap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMDuhmxzRNoLzCG5NlZFkZ82GnKoGS80',
    appId: '1:722218540390:ios:712d080057d1a8a95ebca7',
    messagingSenderId: '722218540390',
    projectId: 'yapo-2e6d1',
    databaseURL: 'https://yapo-2e6d1-default-rtdb.firebaseio.com',
    storageBucket: 'yapo-2e6d1.appspot.com',
    androidClientId: '722218540390-9nuam8t3gekb0un5noeppgorpiktio1h.apps.googleusercontent.com',
    iosClientId: '722218540390-u9ll6m9ern0jcqsqgdpql7ti80v6kbr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.yap.RunnerTests',
  );
}
